### PR TITLE
BradyBeecham-signoff-ChargeController

### PR DESCRIPTION
**Pull request by Brady-Beecham**
Requesting sign off for Charge Controller

### CODE REVIEW

**Review by JesseTNRoberts — COMMENTED** [review]
No buildable schematic. Not a good faith effort.

**Comment by Brady-Beecham** [comment]
Added buildable schematic and analysis section.

**Review by JesseTNRoberts — COMMENTED** [review]
The progress here is good. Implement the updates that were discussed in person and this will be well on the way!

**Review by JesseTNRoberts — COMMENTED** [review]
It looks like there are a few more items to be filled in here? is this complete?

I am very happy with it so far.

**Review by JesseTNRoberts — APPROVED** [review]
This is good design work. It may not work, because it is complicated (and mistakes are easy to make). But we can cross that bridge later.

**Pull request merged**
