### PR TITLE
Abdulrahman alrudayan signoff wall power

### PR DESCRIPTION
**Pull request by Kpk878**

### CODE REVIEW

**Review by JesseTNRoberts — COMMENTED** [review]
The statement of function is to clear. 

This never charges the battery.

**Review by JesseTNRoberts — COMMENTED** [review]
Why is there a rectifier here?

We have talked about wall warts.

**Review by JesseTNRoberts — COMMENTED** [review]
This looks good. How are you going to do the switching? That seems to have been skipped and it needs to be automatic.

**Comment by Kpk878** [comment]
Thank you for the feedback. 
I just did it.

**Review by JesseTNRoberts — APPROVED** [review]

**Pull request merged**
