### PR TITLE
Khalifah_altamimi_signoff_solar_power.md

### PR DESCRIPTION
**Pull request by khalifo2013**
One part is needed to be completed, which is the power controller [ Schematic and Analysis ]. 
Thanks

### CODE REVIEW

**Review by JesseTNRoberts — COMMENTED** [review]
Some of the constraints seem to not be on this subsystem and are instead on the other subsystems that are related. Is this the case? If so, be sure that the constraints here are the constraints on this subsystem.

**Comment by khalifo2013** [comment]
I updated the signoff. 
1- The solar panel increased from 25W to 30 W.
2- The battery needed exact 24Ah and that did not change.

**Review by JesseTNRoberts — COMMENTED** [review]
This needs to be updated so that it is clear what this subsystem actually covers. It seems like it also coverts things in other subsystems.

**Review by JesseTNRoberts — APPROVED** [review]

**Comment by JesseTNRoberts** [comment]
I have approved but there is a conflict that is preventing the merge. This needs to be fixed but in the mean time do the ordering!

**Comment by khalifo2013** [comment]
The pull request had a conflict with merging it to the main.

**Pull request closed without merging**
