### PR TITLE
Khalifa_altamimi-signoff-power-controller

### PR DESCRIPTION
**Pull request by khalifo2013**
requesting signoff for power controller

### CODE REVIEW

**Review by JesseTNRoberts — COMMENTED** [review]
Why three fuses?

**Review by JesseTNRoberts — COMMENTED** [review]
You have not specified fuses etc so this is not buildable.

**Review by JesseTNRoberts — COMMENTED** [review]
This looks great. Can we put this all on a single pCB? That would be best to minimize cost. And that would be very elegant.

I'm happy to signoff now. But for ordering, I would like the PCBs combined into a single PCB. You don't have to change the circuit, only combine them onto one board.

**Comment by khalifo2013** [comment]
I updated the signoff and combined them into a single PCB. I am ready to order.

**Pull request merged**
